name: "🧹 clean & 🛠️ build"

on: 
  push:
    branches:
      - 'main'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
        - name: 📚 checkout
          uses: actions/checkout@v2.5.0
        - name: 🟢 node
          uses: actions/setup-node@v3.5.1
          with:
              node-version: 18
        - name: 📦 pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                version: 7
        - name: 🧹 clean
          run: |
            pnpm clean
            sudo node ./dist/rmrec/index.js ./node_modules
  build:
    needs: clean
    runs-on: ubuntu-latest
    steps:
        - name: 📚 checkout
          uses: actions/checkout@v2.5.0
        - name: 🟢 node
          uses: actions/setup-node@v3.5.1
          with:
              node-version: 18
        - name: 📦 pnpm
          uses: pnpm/action-setup@v2.2.4
          with:
            version: 7
        - name: 🛠️ build
          run: pnpm build